Bash linting

diff --git a/port_docker_image b/port_docker_image
--- a/port_docker_image
+++ b/port_docker_image
@@ -64,30 +64,33 @@ SUBPATH=${SUBPATH:-/}
 ARCH=${ARCH:-$(uname -m)}
 if ( contains "armv7l" "$ARCH" ); then ARCH="armhf"; fi
 BUILDDIR=$(mktemp -d /tmp/port_docker_image.XXXXXXXXXX)
-echo $BUILDDIR
+echo "$BUILDDIR"
 IMAGE_NAME=$(echo "$IMAGE" | cut -d: -f1)
 
 repos=""
 repos="$repos $REPO"
 repos="$repos $IMAGE_NAME"
-repos="$repos $(echo $IMAGE_NAME | sed 's|/|/docker-|')"
+repos="$repos $(echo "$IMAGE_NAME" | sed 's|/|/docker-|')"
 repos="$repos $IMAGE_NAME-docker"
 
-DONE=0
-for repo in $repos; do
-    curl -sL https://github.com/$repo/archive/$BRANCH.tar.gz \
-        | tar --strip-components=1 -C $BUILDDIR -xzf - \
-        && DONE=1 && break || true
-done
-if [ "$DONE" = "0" ]; then
-    echo "Cannot find Github repo." >&2
-    exit 1
-fi
+(
+    set +e
+    DONE=0
+    for repo in $repos; do
+        curl -sL "https://github.com/$repo/archive/$BRANCH.tar.gz" \
+            | tar --strip-components=1 -C "$BUILDDIR" -xzf - \
+            && DONE=1 && break
+    done
+    if [ "$DONE" = "0" ]; then
+        echo "Cannot find Github repo." >&2
+        exit 1
+    fi
+)
 
-cd $BUILDDIR/$SUBPATH
+cd "$BUILDDIR/$SUBPATH"
 
 # Patch Dockerfile
-DOCKERFILE_FROM=$(cat Dockerfile | grep -i ^FROM | awk '{print $2}' | convert_from)
+DOCKERFILE_FROM=$(grep -i ^FROM Dockerfile | awk '{print $2}' | convert_from)
 FROM=${FROM:-$DOCKERFILE_FROM}
 sed -i "s|^[fF][rR][oO][mM].*|FROM $FROM|" Dockerfile
 for old_arch in amd64 x86_64 i386 x86; do
@@ -96,9 +99,9 @@ done
 
 if [ "$DEBUG" = "1" ]; then cat Dockerfile; fi
 
-docker build -t $IMAGE .
-docker tag $IMAGE $(echo $IMAGE | convert_from)
+docker build -t "$IMAGE" .
+docker tag "$IMAGE" "$(echo "$IMAGE" | convert_from)"
 
 if [ "$PUSH" = "1" ]; then
-    docker push $(echo $IMAGE | convert_from)
+    docker push "$(echo "$IMAGE" | convert_from)"
 fi
